title: InkTide
description: Ramblings of yet another scientist
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://priyathamkat.com" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
theme: minima
plugins:
  - jekyll-feed

# Link structure
collections:
    posts:
        permalink: /blog/:title/

    projects:
        permalink: /projects/:title/
        output: true